/* ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¿
   ³                                                                      ³
   ³                  (C) 2000 by TWT The Wonderful Team                  ³
   ³                                                                      ³
   ÀÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ */

#ifndef _DFFILE_CH
   #define _DFFILE_CH

   #define FL_NAME          1 // File name
   #define FL_HANDLE        2 // File Handle
   #define FL_LINE          3 // Actual ROW
   #define FL_BUFFER        4 // Actual Buffer
   #define FL_OFFSET        5 // File Offset
   #define FL_BUFPOS        6 // Buffer Position
   #define FL_EOF           7 // EOF
   #define FL_SEPCHAR       8 // Separator Char
   #define FL_SEPLEN        9 // Separator Lenght
   #define FL_RECLEN       10 // Record Lenght
   #define FL_SKIPREM      11 // Skip comment line

   #define FL_BUFFERLEN  4000 // Buffer Lenght
#endif
