/* ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¿
   ³                                                                      ³
   ³                  (C) 2000 by TWT The Wonderful Team                  ³
   ³                                                                      ³
   ÀÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ */

#ifndef _DFSTACK_CH
   #define _DFSTACK_CH

   // dfPushAct
   #define PA_ACT     1
   #define PA_SA      2
   #define PA_A       3

   // dfPushPal
   #define PAL_ROW    1
   #define PAL_COL    2
   #define PAL_PAL    3
   #define PAL_SCR    4

   // dfPushCursor
   #define ALL_COLOR  1
   #define ALL_ROW    2
   #define ALL_COL    3
   #define ALL_SHAPE  4

   // dfPushArea
   #define PA_ALIAS   1
   #define PA_ORDER   2
   #define PA_RECNO   3

   // dbScr
   #define SCR_NAME    1
   #define SCR_SAV     2
   #define SCR_TOP     3
   #define SCR_LEFT    4
   #define SCR_BOTTOM  5
   #define SCR_RIGHT   6

#endif
